// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EditFeelingPhotoController from "./edit_feeling_photo_controller"
application.register("edit-feeling-photo", EditFeelingPhotoController)

import FeelingImageController from "./feeling_image_controller"
application.register("feeling-image", FeelingImageController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import UserImageController from "./user_image_controller"
application.register("user-image", UserImageController)
